# Generated by Django 5.2.7 on 2025-10-05 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campuspass', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
