# Generated by Django 5.2.7 on 2025-11-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDismissedNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_username', models.TextField()),
                ('log_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'admin_dismissed_notifications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('actor', models.TextField()),
                ('action_type', models.TextField()),
                ('description', models.TextField()),
                ('actor_role', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'system_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('visit_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_email', models.TextField()),
                ('code', models.TextField(unique=True)),
                ('purpose', models.TextField()),
                ('department', models.TextField()),
                ('visit_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('status', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'visits',
                'managed': False,
            },
        ),
    ]
