# Generated by Django 5.2.7 on 2025-11-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('admin_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('username', models.TextField(unique=True)),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('contact_number', models.TextField()),
                ('is_superadmin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_temp_password', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'administrator',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FrontDeskStaff',
            fields=[
                ('staff_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('username', models.TextField(unique=True)),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('contact_number', models.TextField()),
                ('is_temp_password', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'front_desk_staff',
                'managed': False,
            },
        ),
    ]
